services:
  - type: web
    name: ecommerce-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/products
    envVars:
      - key: PORT
        value: "8080"
      - key: DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: JWT_SECRET
        generateValue: true
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false
